[project]
name = "mozzarella"
version = "0.1.1"
description = "Use procedural macros in Python"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "executing>=2.1.0",
]

[tool.ruff.lint]
select = ["ANN"]
ignore = ["ANN401"]

[dependency-groups]
dev = [
    "ruff>=0.8.4",
]
