"""
THIS FILE IS GENERATED BY A MACRO. DO NOT EDIT.
"""

import typing

if typing.TYPE_CHECKING:
    from mozzarella import macro
    import re

    def gen_my_other_func(a: int, b: int) -> str:
        return str(a - 3 - b)
else:
    gen_my_other_func = None

if typing.TYPE_CHECKING:
    from mozzarella import macro
    import re

    def gen_my_func(a: int, b: int) -> str:
        return str(a - b)
else:
    gen_my_func = None

if typing.TYPE_CHECKING:
    from mozzarella import macro
    import re

    class GenStuff:
        def __init__(self, c: int) -> None:
            self.c = c

        def my_method(self, a: int, b: int) -> str:
            return str(a - b - self.c)

        @property
        def whatever(self) -> str:
            self.my_method(1, 2)
            return str(4)
else:

    class GenStuff:
        pass
